create database EXAMEN;
use EXAMEN;
create table ESTUDIANTES(
idest INT NOT NULL PRIMARY KEY,
nombre VARCHAR(12)NOT NULL,
apellido VARCHAR(12)NOT NULL,
nota INT NOT NULL,
curso VARCHAR(40)NOT NULL);
SHOW COLUMNS FROM ESTUDIANTES;